export type SharedNodeType = "trigger"|"action"|"condition"|"approval"|"api"|"webhook"|"database"|"notification"|"delay"|"join"|"end";
export type SharedBranch = "DEFAULT"|"TRUE"|"FALSE"|"APPROVED"|"REJECTED"|"TIMEOUT"|string;
export type SharedNode = { id:string; type:SharedNodeType; name:string; description?:string; config?:Record<string,unknown> };
export type SharedEdge = { source:string; target:string; branch?:SharedBranch };
import { nodeContractIssues } from "./node-contracts";
import { buildRequirementContract } from "./requirement-contract";

export type SharedRuleFinding = {
  id:string;
  severity:"error"|"warning";
  title:string;
  category:string;
  reason:string;
  affected:string[];
  suggestedFix:string;
};

const STOPWORDS = new Set(["the","a","an","to","it","their","them","of","on","in","for","and","then","if","is","are","was","were","be","new","when","otherwise","else","day","one"]);
const VERBS = /\b(create|assign|notify|email|message|alert|schedule|classify|escalate|route|send|check|verify|validate|update|save|store|call|request|obtain|extract|match|process|record|open|close|archive|log|publish|sync|upload|download|transform|convert)\b/i;
const COMMUNICATION = /\b(notify|notification|email|e-mail|alert|sms|slack|inform|contact|send\s+(?:an?\s+)?(?:email|message|notification|sms|alert))\b/i;
const TERMINAL_CAPABLE = new Set<SharedNodeType>(["end","action","api","webhook","database","notification"]);

function tokens(v:string): string[] { return String(v||"").toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(x=>x.length>2&&!STOPWORDS.has(x)); }
function nodeText(n:SharedNode){ return `${n.name} ${n.description||""} ${Object.values(n.config||{}).join(" ")}`; }
type SemanticMatch={node?:SharedNode; ambiguous:SharedNode[]; score:number};
function semanticMatch(nodes:SharedNode[], phrase:string, allowed?:Set<SharedNodeType>):SemanticMatch{
  const want=tokens(phrase); if(!want.length)return {ambiguous:[],score:0};
  const normalized=tokens(phrase).join(" ");
  const candidates=nodes.filter(n=>!allowed||allowed.has(n.type)).map(n=>{
    const have=tokens(nodeText(n)), name=tokens(n.name).join(" ");
    const overlap=want.filter(t=>have.includes(t)).length;
    const precision=overlap/Math.max(1,have.length), recall=overlap/Math.max(1,want.length);
    const score=name===normalized?2:(recall*0.75+precision*0.25);
    return {n,score};
  }).filter(x=>x.score>=0.45).sort((a,b)=>b.score-a.score);
  if(!candidates.length)return {ambiguous:[],score:0};
  if(candidates[0].score>=1.99)return {node:candidates[0].n,ambiguous:[],score:candidates[0].score};
  const close=candidates.filter(x=>candidates[0].score-x.score<=0.08);
  if(close.length>1)return {ambiguous:close.map(x=>x.n),score:candidates[0].score};
  return {node:candidates[0].n,ambiguous:[],score:candidates[0].score};
}
function findNode(nodes:SharedNode[], phrase:string, allowed?:Set<SharedNodeType>){return semanticMatch(nodes,phrase,allowed).node;}
function splitActions(clause:string): string[]{
  const cleaned=String(clause||"").replace(/[.]+$/g,"").trim();
  return cleaned.split(/\s*,\s*|\s+and\s+(?=(?:create|assign|notify|email|message|alert|schedule|classify|escalate|route|send|check|verify|validate|update|save|store|call|request|obtain|extract|match|process|record|open|close|archive|log|publish|sync|upload|download|transform|convert)\b)/i).map(x=>x.trim()).filter(x=>VERBS.test(x));
}
function hasCycle(nodes:SharedNode[], edges:SharedEdge[]){
  const out=new Map<string,string[]>();for(const e of edges){if(!out.has(e.source))out.set(e.source,[]);out.get(e.source)!.push(e.target);}const visiting=new Set<string>(),visited=new Set<string>();
  const dfs=(id:string):boolean=>{if(visiting.has(id))return true;if(visited.has(id))return false;visiting.add(id);for(const n of out.get(id)||[])if(dfs(n))return true;visiting.delete(id);visited.add(id);return false;};
  return nodes.some(n=>dfs(n.id));
}
function stringConfig(config:Record<string,unknown>={}):Record<string,string>{const out:Record<string,string>={};for(const [k,v] of Object.entries(config)){if(v!==undefined&&v!==null)out[k]=typeof v==="string"?v:JSON.stringify(v);}return out;}
function cycleComponents(nodes:SharedNode[], edges:SharedEdge[]):string[][]{
  const out=new Map<string,string[]>();for(const n of nodes)out.set(n.id,[]);for(const e of edges)out.get(e.source)?.push(e.target);
  const index=new Map<string,number>(),low=new Map<string,number>(),stack:string[]=[],onStack=new Set<string>();let next=0;const comps:string[][]=[];
  const visit=(id:string)=>{index.set(id,next);low.set(id,next);next++;stack.push(id);onStack.add(id);for(const t of out.get(id)||[]){if(!index.has(t)){visit(t);low.set(id,Math.min(low.get(id)!,low.get(t)!));}else if(onStack.has(t))low.set(id,Math.min(low.get(id)!,index.get(t)!));}if(low.get(id)===index.get(id)){const c:string[]=[];let w="";do{w=stack.pop()!;onStack.delete(w);c.push(w);}while(w!==id);comps.push(c);}};
  for(const n of nodes)if(!index.has(n.id))visit(n.id);return comps.filter(c=>c.length>1||edges.some(e=>e.source===c[0]&&e.target===c[0]));
}

export function isCommunicationIntent(text:string){
  const s=String(text||"");
  if(/\bmessage\s+queue\b/i.test(s)) return false;
  return COMMUNICATION.test(s);
}

export function evaluateSharedStructuralRules(prompt:string,nodes:SharedNode[],edges:SharedEdge[]):SharedRuleFinding[]{
  const findings:SharedRuleFinding[]=[];const byId=new Map(nodes.map(n=>[n.id,n]));const incoming=new Map<string,SharedEdge[]>(),outgoing=new Map<string,SharedEdge[]>();
  for(const n of nodes){incoming.set(n.id,[]);outgoing.set(n.id,[]);}for(const e of edges){outgoing.get(e.source)?.push(e);incoming.get(e.target)?.push(e);if(!byId.has(e.source))findings.push({id:`undefined-source-${e.source}`,severity:"error",title:"Undefined Edge Source",category:"Graph Integrity",reason:`Edge source '${e.source}' does not exist.`,affected:[e.source],suggestedFix:"Define the source node or remove the edge."});if(!byId.has(e.target))findings.push({id:`undefined-target-${e.target}`,severity:"error",title:"Undefined Edge Target",category:"Graph Integrity",reason:`Edge target '${e.target}' does not exist.`,affected:[e.target],suggestedFix:"Define the target node or remove the edge."});}
  const triggers=nodes.filter(n=>n.type==="trigger");if(!triggers.length)findings.push({id:"missing-trigger",severity:"error",title:"Missing Trigger",category:"Structure",reason:"Workflow has no trigger node.",affected:[],suggestedFix:"Add a trigger and connect it to the first executable step."});
  if(triggers.length>1){const explicitMulti=/\b(multiple triggers|either when|when .+ or when|on either|separate triggers)\b/i.test(prompt);findings.push({id:"multiple-triggers",severity:explicitMulti?"warning":"error",title:explicitMulti?"Multiple Triggers":"Unexpected Multiple Triggers",category:"Structure",reason:explicitMulti?"Multiple entry points are allowed when intentionally designed.":"The original requirement defines one entry event, but the graph contains multiple trigger nodes.",affected:triggers.map(n=>n.id),suggestedFix:explicitMulti?"Confirm that each trigger is intentional.":"Keep the trigger matching the stated entry event and re-type/reconnect any action misclassified as a trigger."});}
  if(triggers.length){const seen=new Set<string>(),q=triggers.map(n=>n.id);while(q.length){const id=q.shift()!;if(seen.has(id))continue;seen.add(id);for(const e of outgoing.get(id)||[])q.push(e.target);}const unreachable=nodes.filter(n=>!seen.has(n.id));if(unreachable.length)findings.push({id:"unreachable",severity:"error",title:"Unreachable Nodes",category:"Graph Integrity",reason:"Some nodes cannot be reached from any trigger.",affected:unreachable.map(n=>n.id),suggestedFix:"Reconnect required nodes to the intended execution path or remove only truly extraneous nodes."});}
  const terminalLeaves=nodes.filter(n=>TERMINAL_CAPABLE.has(n.type)&&!(outgoing.get(n.id)||[]).length);if(nodes.length&&!terminalLeaves.length)findings.push({id:"missing-end",severity:"error",title:"Missing Terminal Path",category:"Execution Safety",reason:"No explicit END node or terminal-capable final action can complete the workflow.",affected:[],suggestedFix:"Ensure at least one reachable path completes at END or a valid final action."});
  for(const n of nodes){const ins=incoming.get(n.id)||[],outs=outgoing.get(n.id)||[];
    if(n.type!=="trigger"&&n.type!=="end"&&!ins.length)findings.push({id:`orphan-${n.id}`,severity:"error",title:`Orphan Node: ${n.name}`,category:"Graph Integrity",reason:"This node has no incoming connection.",affected:[n.id],suggestedFix:"Reconnect this required step to its semantic predecessor."});
    if(n.type==="action"&&isCommunicationIntent(nodeText(n)))findings.push({id:`communication-type-${n.id}`,severity:"error",title:`Communication Must Use Notification: ${n.name}`,category:"Node Contract",reason:"Communication intent must be represented by a Notification node.",affected:[n.id],suggestedFix:"Change this node to Notification and preserve its incoming/outgoing connections."});
    const notificationMisclassified=n.type==="notification"&&!isCommunicationIntent(nodeText(n));
    if(notificationMisclassified)findings.push({id:`notification-type-${n.id}`,severity:"error",title:`Business Action Misclassified As Notification: ${n.name}`,category:"Node Contract",reason:"This node has no communication intent. Under Rule Book v2.0, ordinary business operations must remain Action nodes and must not be forced to provide a notification recipient.",affected:[n.id],suggestedFix:"Change this node to Action and preserve its semantic intent, configuration, and connections."});
    if(n.type==="condition"){const labels=outs.map(e=>String(e.branch||"DEFAULT").toUpperCase());if(!labels.includes("TRUE")||!labels.includes("FALSE"))findings.push({id:`condition-branches-${n.id}`,severity:"error",title:`Incomplete Condition: ${n.name}`,category:"Branch Safety",reason:"A condition must define both TRUE and FALSE outcomes.",affected:[n.id],suggestedFix:"Add explicit TRUE and FALSE branches grounded in the original requirement."});if(labels.filter(x=>x==="TRUE").length>1||labels.filter(x=>x==="FALSE").length>1)findings.push({id:`condition-duplicate-${n.id}`,severity:"error",title:`Duplicate Condition Branch: ${n.name}`,category:"Branch Safety",reason:"A condition has more than one target for the same TRUE/FALSE outcome.",affected:[n.id],suggestedFix:"Keep one semantic target per TRUE/FALSE outcome."});}
    if(n.type==="condition"){const expr=String((n.config||{}).Expression??(n.config||{}).expression??"").trim();if(!expr)findings.push({id:`condition-expression-${n.id}`,severity:"error",title:`Undefined Condition: ${n.name}`,category:"Ambiguity",reason:"The condition node has no machine-evaluable expression.",affected:[n.id],suggestedFix:"Define an expression grounded in the original requirement; do not invent missing thresholds."});}
    if(n.type==="approval"){const labels=outs.map(e=>String(e.branch||"DEFAULT").toUpperCase());if(!labels.includes("APPROVED")||!labels.includes("REJECTED"))findings.push({id:`approval-branches-${n.id}`,severity:"error",title:`Incomplete Approval: ${n.name}`,category:"Branch Safety",reason:"Approval must define APPROVED and REJECTED outcomes.",affected:[n.id],suggestedFix:"Add both approval outcomes without inventing missing business policy."});const role=String((n.config||{}).Role??(n.config||{}).role??"").trim();if(!role){const contract=buildRequirementContract(prompt);const roleMatches=contract.approvalRoles.filter(r=>tokens(r.approvalPhrase).some(t=>tokens(nodeText(n)).includes(t)));
      const rc=roleMatches.length===1?roleMatches[0]:(contract.approvalRoles.length===1?contract.approvalRoles[0]:undefined);if(rc?.role)findings.push({id:`approval-role-${n.id}`,severity:"error",title:`Missing Approval Role: ${n.name}`,category:"Authorization",reason:`The requirement explicitly identifies ${rc.role} as the approver, but the node has no Role.`,affected:[n.id],suggestedFix:`Set Role to ${rc.role}; this is grounded in the original requirement.`});else findings.push({id:`approval-role-${n.id}`,severity:"warning",title:`Approval Role Needs User Input: ${n.name}`,category:"User Input Required",reason:"The requirement asks for approval but does not identify who is authorized to approve it.",affected:[n.id],suggestedFix:"Ask the user to specify the approver role. Do not invent a role."});}}
    if(n.type==="end"&&outs.length)findings.push({id:`end-out-${n.id}`,severity:"error",title:`End Node Has Output: ${n.name}`,category:"Execution Safety",reason:"Terminal nodes should not continue execution.",affected:[n.id],suggestedFix:"Remove outgoing edges from this END node."});
    if(n.type==="join"){const nonDefault=ins.concat(outs).filter(e=>String(e.branch||"DEFAULT").toUpperCase()!=="DEFAULT");const mode=String((n.config||{}).JoinMode||(n.config||{}).Mode||"BARRIER").toUpperCase();if(ins.length<2)findings.push({id:`join-inputs-${n.id}`,severity:"error",title:`Incomplete ${mode==="MERGE"?"Merge":"Join"}: ${n.name}`,category:"Parallel Semantics",reason:"A synchronization node must have at least two incoming paths.",affected:[n.id],suggestedFix:"Connect every intended branch into this synchronization node."});if(outs.length>1)findings.push({id:`join-outputs-${n.id}`,severity:"error",title:`Invalid Join Output: ${n.name}`,category:"Parallel Semantics",reason:"A Join/Merge may continue through at most one DEFAULT successor.",affected:[n.id],suggestedFix:"Keep one continuation edge after synchronization."});if(nonDefault.length)findings.push({id:`join-branches-${n.id}`,severity:"error",title:`Invalid Join Branch Labels: ${n.name}`,category:"Parallel Semantics",reason:"Synchronization edges must use DEFAULT; decision labels belong to the upstream decision node.",affected:[n.id],suggestedFix:"Use DEFAULT edges into and out of the Join/Merge."});if(!["BARRIER","MERGE"].includes(mode))findings.push({id:`join-mode-${n.id}`,severity:"error",title:`Invalid Join Mode: ${n.name}`,category:"Parallel Semantics",reason:"JoinMode must be BARRIER (wait for all sibling parallel branches) or MERGE (continue after one exclusive decision branch).",affected:[n.id],suggestedFix:"Set JoinMode to BARRIER or MERGE."});}
    if(!TERMINAL_CAPABLE.has(n.type)&&n.type!=="trigger"&&!outs.length)findings.push({id:`deadend-${n.id}`,severity:"error",title:`Unsafe Dead End: ${n.name}`,category:"Execution Safety",reason:"This node cannot safely terminate execution.",affected:[n.id],suggestedFix:"Connect it to the intended successor or terminal state."});
    const cfg=stringConfig(n.config||{});if(!notificationMisclassified)for(const [idx,c] of nodeContractIssues(n.type as any,n.name,n.description||"",cfg).entries())findings.push({id:`config-${n.id}-${idx}`,severity:c.severity,title:`Incomplete ${n.type.toUpperCase()} Node: ${n.name}`,category:"Node Configuration",reason:c.reason,affected:[n.id],suggestedFix:c.fix});
    const has=(...ks:string[])=>ks.some(k=>String(cfg[k]??"").trim());
    if(n.type==="webhook"&&!has("Operation","URL","Url","url","Path","path","Event","event","Mode","mode"))findings.push({id:`config-${n.id}-webhook`,severity:"warning",title:`Incomplete WEBHOOK Node: ${n.name}`,category:"Node Configuration",reason:"Webhook node has no send/receive intent or endpoint/path configuration.",affected:[n.id],suggestedFix:"Define webhook mode and logical destination/event. Concrete deployment URL/path may be supplied later."});
    if(n.type==="database"&&!has("Operation","Query","query","Table","table","Collection","collection","Resource","resource"))findings.push({id:`config-${n.id}-database`,severity:"warning",title:`Incomplete DATABASE Node: ${n.name}`,category:"Node Configuration",reason:"Database node has no logical data operation defined.",affected:[n.id],suggestedFix:"Define read/write/update/delete and the logical resource. Connection details may be supplied later."});
    if(n.type==="action"&&!has("Operation","operation"))findings.push({id:`config-${n.id}-action`,severity:"warning",title:`Incomplete ACTION Node: ${n.name}`,category:"Node Configuration",reason:"Action node has no explicit operation identifier.",affected:[n.id],suggestedFix:"Define the logical operation this action performs."});
  }
  const lower=prompt.toLowerCase();const count=(t:SharedNodeType)=>nodes.filter(n=>n.type===t).length;
  if(/\b(database|db|firestore|mysql|postgres|sql|inventory database)\b/i.test(prompt)&&count("database")===0)findings.push({id:"requirement-database",severity:"error",title:"Missing Database Step",category:"Requirement Coverage",reason:"The original requirement explicitly uses a database but the workflow has no Database node.",affected:[],suggestedFix:"Add a dedicated Database node at the stated point in the process."});
  if(/\b(api|endpoint|http request|rest api)\b/i.test(prompt)&&count("api")===0)findings.push({id:"requirement-api",severity:"error",title:"Missing API Step",category:"Requirement Coverage",reason:"The original requirement explicitly uses an API but the workflow has no API node.",affected:[],suggestedFix:"Add a dedicated API node at the stated point in the process."});
  if(/\bwebhook\b/i.test(prompt)&&count("webhook")===0)findings.push({id:"requirement-webhook",severity:"error",title:"Missing Webhook Step",category:"Requirement Coverage",reason:"The original requirement explicitly uses a webhook but the workflow has no Webhook node.",affected:[],suggestedFix:"Add a dedicated Webhook node."});
  if(/\b(wait|delay|pause|after \d+ (?:seconds?|minutes?|hours?|days?))\b/i.test(prompt)&&count("delay")===0)findings.push({id:"requirement-delay",severity:"error",title:"Missing Delay Step",category:"Requirement Coverage",reason:"The original requirement explicitly contains a wait/delay but the workflow has no Delay node.",affected:[],suggestedFix:"Add a Delay node with the stated duration."});
  const notifyMentions=(lower.match(/\b(?:notify|notification|email|e-mail|message|alert|sms|slack|inform|contact|send (?:an? )?(?:email|message|notification|sms|alert))\b/g)||[]).length;const notif=count("notification");
  if(notifyMentions>0&&notif===0)findings.push({id:"requirement-notification",severity:"error",title:"Missing Notification Step",category:"Requirement Coverage",reason:"The original requirement explicitly requests communication but the workflow has no Notification node.",affected:[],suggestedFix:"Represent notify/email/message/alert behavior with Notification nodes."});else if(notifyMentions>=2&&notif<2)findings.push({id:"requirement-notification-count",severity:"error",title:"Missing Notification Actions",category:"Requirement Coverage",reason:`The requirement contains ${notifyMentions} communication actions but the workflow has only ${notif} Notification node(s).`,affected:[],suggestedFix:"Represent each distinct requested communication action on its correct branch."});
  if(/\b(repeat|repeating|retry|again|keep checking|keep repeating|continue until|until|while)\b/i.test(prompt)&&!hasCycle(nodes,edges))findings.push({id:"requirement-loop",severity:"error",title:"Missing Loop Structure",category:"Requirement Coverage",reason:"The original requirement explicitly describes repetition/until logic but the workflow has no loop-back edge.",affected:[],suggestedFix:"Add the stated repeat path with a condition-controlled exit."});

  const trigger=triggers[0];const edge=(a:string,b:string,branch?:string)=>edges.some(e=>e.source===a&&e.target===b&&(!branch||String(e.branch||"DEFAULT").toUpperCase()===branch));const sentences=prompt.replace(/\s+/g," ").split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(Boolean);const first=sentences[0]||"";
  // Only infer parallel fan-out when the wording strongly suggests a sibling list.
  // Two actions joined by "and" are often sequential ("extract total and save it",
  // "create PO and notify finance"), so do NOT force fan-out for two-action clauses.
  if(trigger&&sentences.length===1&&!/\b(if|else|otherwise|then|after|before|once\b.*\bcomplete)/i.test(first)){
    const m=first.match(/^(?:when|whenever|once|on)\s+.+?,\s*(.+)$/i);
    const actionClause=m?.[1]||""; const actions=splitActions(actionClause);
    const explicitParallel=/\b(in parallel|simultaneously|at the same time|concurrently)\b/i.test(actionClause);
    const siblingList=false; // Parallelism is never inferred from punctuation alone.
    const allowed=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay"]);
    const matched=actions.map(a=>findNode(nodes,a,allowed)).filter(Boolean) as SharedNode[];
    if(explicitParallel&&matched.length>=2&&!matched.every(n=>edge(trigger.id,n.id,"DEFAULT")))findings.push({id:"intent-fanout",severity:"error",title:"Explicit Parallel Actions Are Incorrectly Serialized",category:"Requirement Structure",reason:`The requirement explicitly requests parallel execution, but the graph does not fan those actions out from trigger '${trigger.id}'.`,affected:matched.map(n=>n.id),suggestedFix:"Connect each explicitly parallel action from the trigger."});
  }
  for(let i=1;i<sentences.length;i++){
    const cm=sentences[i].match(/^if\s+(.+?)(?:,|\bthen\b)\s*(.+?)(?:\s*(?:,|;)\s*(?:else|otherwise)\s+(.+))?$/i);if(!cm)continue;
    // "If approved/rejected" is an approval outcome, not another condition. Binding it to
    // the only condition in the graph can bypass the approval node and corrupt the workflow.
    const approvalOutcome=cm[1].trim().match(/^(?:it\s+is\s+)?(approved|accepted|rejected|denied|declined)$/i);
    if(approvalOutcome){
      const approvals=nodes.filter(n=>n.type==="approval");
      if(approvals.length===1){
        const approval=approvals[0]; const branch=/approved|accepted/i.test(approvalOutcome[1])?"APPROVED":"REJECTED";
        const allowed=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay","end"]);
        const branchNodes=splitActions(cm[2]).map(x=>findNode(nodes,x,allowed)).filter(Boolean) as SharedNode[];
        if(branchNodes[0]&&!edge(approval.id,branchNodes[0].id,branch))findings.push({id:`intent-${branch.toLowerCase()}-${approval.id}`,severity:"error",title:`${branch} Branch Is Misconnected`,category:"Requirement Structure",reason:`The stated ${branch} action '${branchNodes[0].name}' is not connected from approval '${approval.name}'.`,affected:[approval.id,branchNodes[0].id],suggestedFix:`Connect ${approval.id} --${branch}--> ${branchNodes[0].id}.`});
        for(let j=1;j<branchNodes.length;j++)if(!edge(branchNodes[j-1].id,branchNodes[j].id,"DEFAULT"))findings.push({id:`intent-${branch.toLowerCase()}-seq-${approval.id}-${j}`,severity:"error",title:`${branch} Branch Sequence Is Incomplete`,category:"Requirement Structure",reason:`The original wording requires '${branchNodes[j-1].name}' followed by '${branchNodes[j].name}'.`,affected:[branchNodes[j-1].id,branchNodes[j].id],suggestedFix:`Connect ${branchNodes[j-1].id} → ${branchNodes[j].id}.`});
      }
      continue;
    }
    const prevActions=splitActions(sentences[i-1].replace(/^(?:when|whenever|once|on)\s+.+?,\s*/i,""));const allowedPre=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay"]);const prev=prevActions.length?findNode(nodes,prevActions[prevActions.length-1],allowedPre):undefined;let cond=findNode(nodes,cm[1],new Set<SharedNodeType>(["condition"]));if(!cond){const conditions=nodes.filter(n=>n.type==="condition");if(conditions.length===1)cond=conditions[0];}if(!cond)continue;if(prev&&!edge(prev.id,cond.id,"DEFAULT"))findings.push({id:`intent-anchor-${cond.id}`,severity:"error",title:"Prerequisite Not Connected To Decision",category:"Requirement Structure",reason:`The prerequisite '${prev.name}' must feed condition '${cond.name}' before branching.`,affected:[prev.id,cond.id],suggestedFix:`Connect ${prev.id} → ${cond.id} with DEFAULT.`});const allowed=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay","approval"]);const trueNodes=splitActions(cm[2]).map(x=>findNode(nodes,x,allowed)).filter(Boolean) as SharedNode[];if(trueNodes[0]&&!edge(cond.id,trueNodes[0].id,"TRUE"))findings.push({id:`intent-true-${cond.id}`,severity:"error",title:"TRUE Branch Is Misconnected",category:"Requirement Structure",reason:`The stated TRUE action '${trueNodes[0].name}' is not connected from condition '${cond.name}'.`,affected:[cond.id,trueNodes[0].id],suggestedFix:`Connect ${cond.id} --TRUE--> ${trueNodes[0].id}.`});for(let j=1;j<trueNodes.length;j++)if(!edge(trueNodes[j-1].id,trueNodes[j].id,"DEFAULT"))findings.push({id:`intent-true-seq-${cond.id}-${j}`,severity:"error",title:"TRUE Branch Sequence Is Incomplete",category:"Requirement Structure",reason:`The original wording requires '${trueNodes[j-1].name}' followed by '${trueNodes[j].name}'.`,affected:[trueNodes[j-1].id,trueNodes[j].id],suggestedFix:`Connect ${trueNodes[j-1].id} → ${trueNodes[j].id}.`});const falseNodes=(cm[3]?splitActions(cm[3]):[]).map(x=>findNode(nodes,x,allowed)).filter(Boolean) as SharedNode[];if(falseNodes[0]&&!edge(cond.id,falseNodes[0].id,"FALSE"))findings.push({id:`intent-false-${cond.id}`,severity:"error",title:"FALSE Branch Is Misconnected",category:"Requirement Structure",reason:`The stated FALSE/otherwise action '${falseNodes[0].name}' is not connected from condition '${cond.name}'.`,affected:[cond.id,falseNodes[0].id],suggestedFix:`Connect ${cond.id} --FALSE--> ${falseNodes[0].id}.`});for(let j=1;j<falseNodes.length;j++)if(!edge(falseNodes[j-1].id,falseNodes[j].id,"DEFAULT"))findings.push({id:`intent-false-seq-${cond.id}-${j}`,severity:"error",title:"FALSE Branch Sequence Is Incomplete",category:"Requirement Structure",reason:`The original wording requires '${falseNodes[j-1].name}' followed by '${falseNodes[j].name}'.`,affected:[falseNodes[j-1].id,falseNodes[j].id],suggestedFix:`Connect ${falseNodes[j-1].id} → ${falseNodes[j].id}.`});
  }
  // Explicit I/O outcome contract: TRUE means success, FALSE means failure.
  for(const n of nodes.filter(n=>!["condition","approval"].includes(n.type))){const outs=outgoing.get(n.id)||[];const labels=outs.map(e=>String(e.branch||"DEFAULT").toUpperCase());if(labels.some(x=>x!=="DEFAULT"))findings.push({id:`nondecision-branch-${n.id}`,severity:"error",title:`Invalid Outcome Branch On Non-Decision Node: ${n.name}`,category:"Execution Contract",reason:"Only Condition and Approval nodes own semantic outcome branches. Ordinary action, I/O, notification, trigger, delay, join, and end edges use DEFAULT.",affected:[n.id],suggestedFix:"Use a DEFAULT edge here. If business routing is required, represent the decision explicitly with a Condition or Approval node."});}
  // Explicit parallel execution may either terminate independently or synchronize through a first-class Join barrier.
  const explicitParallelPrompt=/\b(in parallel|simultaneously|concurrently|at the same time)\b/i.test(prompt);
  const reachableJoin=(start:string)=>{const q=[start],seen=new Set<string>();while(q.length){const id=q.shift()!;if(seen.has(id))continue;seen.add(id);const nd=byId.get(id);if(nd?.type==="join")return id;for(const e of outgoing.get(id)||[])if(String(e.branch||"DEFAULT").toUpperCase()==="DEFAULT")q.push(e.target);}return undefined;};
  const pathReaches=(start:string,target:string)=>{const q=[start],seen=new Set<string>();while(q.length){const id=q.shift()!;if(id===target)return true;if(seen.has(id))continue;seen.add(id);for(const e of outgoing.get(id)||[])q.push(e.target);}return false;};
  for(const j of nodes.filter(n=>n.type==="join")){
    const mode=String((j.config||{}).JoinMode||(j.config||{}).Mode||"BARRIER").toUpperCase();
    const ins=incoming.get(j.id)||[];
    const decisionAncestors=nodes.filter(n=>{
      if(!["condition","approval"].includes(n.type))return false;
      const decisionOuts=(outgoing.get(n.id)||[]).filter(e=>["TRUE","FALSE","APPROVED","REJECTED","TIMEOUT"].includes(String(e.branch||"").toUpperCase()));
      return decisionOuts.filter(e=>pathReaches(e.target,j.id)).length>=2;
    });
    if(mode==="BARRIER"&&decisionAncestors.length)findings.push({id:`join-exclusive-${j.id}`,severity:"error",title:`Barrier Join Uses Mutually Exclusive Branches: ${j.name}`,category:"Parallel Semantics",reason:"A BARRIER waits for all inputs, but these inputs come from mutually exclusive condition/approval outcomes. This can deadlock.",affected:[j.id,...decisionAncestors.map(n=>n.id)],suggestedFix:"Use JoinMode=MERGE for exclusive decision branches, or redesign them as true parallel branches."});
    if(mode==="BARRIER"&&!decisionAncestors.length){
      const splits=nodes.filter(n=>!["condition","approval","join","end"].includes(n.type)).map(n=>({n,outs:(outgoing.get(n.id)||[]).filter(e=>String(e.branch||"DEFAULT").toUpperCase()==="DEFAULT")})).filter(x=>x.outs.length>=2&&x.outs.filter(e=>pathReaches(e.target,j.id)).length>=2);
      if(splits.length!==1)findings.push({id:`join-membership-${j.id}`,severity:"error",title:`Join Branch Membership Is Ambiguous: ${j.name}`,category:"Parallel Semantics",reason:splits.length?"More than one parallel split could claim this Join; branch identity is ambiguous.":"No single parallel fan-out can be proven to own all inputs of this Join.",affected:[j.id,...ins.map(e=>e.source)],suggestedFix:"Connect this BARRIER to complete sibling branches from exactly one explicit parallel split."});
      else{
        const roots=splits[0].outs.filter(e=>pathReaches(e.target,j.id)).map(e=>e.target);
        const unrelated=ins.filter(e=>!roots.some(r=>r===e.source||pathReaches(r,e.source)));
        if(unrelated.length)findings.push({id:`join-unrelated-input-${j.id}`,severity:"error",title:`Join Contains Unrelated Input: ${j.name}`,category:"Parallel Semantics",reason:"At least one Join input is not part of a branch owned by the same parallel split.",affected:[j.id,...unrelated.map(e=>e.source)],suggestedFix:"Remove unrelated Join inputs or connect them through the correct parallel split."});
      }
    }
    if(mode==="MERGE"&&!decisionAncestors.length)findings.push({id:`merge-no-decision-${j.id}`,severity:"error",title:`Merge Has No Exclusive Decision Source: ${j.name}`,category:"Parallel Semantics",reason:"MERGE is only valid for paths that originate from mutually exclusive outcomes of the same condition or approval.",affected:[j.id,...ins.map(e=>e.source)],suggestedFix:"Use BARRIER for parallel siblings, or connect this MERGE to exclusive branches from one decision node."});
  }
  for(const n of nodes.filter(n=>!["condition","approval","join"].includes(n.type))){const outs=(outgoing.get(n.id)||[]).filter(e=>String(e.branch||"DEFAULT").toUpperCase()==="DEFAULT");if(outs.length<=1)continue;const targets=outs.map(e=>byId.get(e.target)).filter(Boolean) as SharedNode[];const terminalFanout=targets.length===outs.length&&targets.every(t=>TERMINAL_CAPABLE.has(t.type)&&!(outgoing.get(t.id)||[]).length);const joins=outs.map(e=>reachableJoin(e.target));const sharedJoin=joins.length===outs.length&&Boolean(joins[0])&&joins.every(j=>j===joins[0]);if(!explicitParallelPrompt)findings.push({id:`unexpected-fanout-${n.id}`,severity:"error",title:`Unexpected Parallel Fan-Out: ${n.name}`,category:"Parallel Semantics",reason:"The graph has multiple simultaneous DEFAULT outputs, but the requirement does not explicitly request parallel execution.",affected:[n.id,...targets.map(t=>t.id)],suggestedFix:"Restore a deterministic sequence, or explicitly request parallel execution."});else if(!terminalFanout&&!sharedJoin)findings.push({id:`parallel-missing-join-${n.id}`,severity:"error",title:`Parallel Branches Do Not Synchronize: ${n.name}`,category:"Parallel Semantics",reason:"Explicit parallel branches continue, but they do not converge on one Join barrier.",affected:[n.id,...targets.map(t=>t.id)],suggestedFix:"Connect all parallel branches to one Join node before continuing."});}
  // First-class requirement contract: deterministic ordering/dependency and branch-position checks.
  const contract=buildRequirementContract(prompt);
  // Semantic identity must never silently select between similarly plausible nodes.
  const semanticKinds=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay","approval","condition"]);
  for(let i=0;i<(contract.requiredActions||[]).length;i++){
    const phrase=String(contract.requiredActions[i]); const m=semanticMatch(nodes,phrase,semanticKinds);
    if(m.ambiguous.length>1)findings.push({id:`ambiguous-required-${i}`,severity:"warning",title:"Ambiguous Requirement-to-Node Match",category:"User Input Required",reason:`'${phrase}' matches multiple workflow nodes with similar confidence: ${m.ambiguous.map(n=>n.name).join(", ")}. FlowForge will not silently choose one.`,affected:m.ambiguous.map(n=>n.id),suggestedFix:"Clarify which workflow step satisfies this requirement, or rename/configure the intended node so its semantic identity is unique."});
    else if(!m.node)findings.push({id:`missing-required-${i}`,severity:"error",title:`Missing Required Action: ${phrase}`,category:"Requirement Closure",reason:`The original requirement explicitly requires '${phrase}', but no workflow node is mapped to that actionable intent.`,affected:[],suggestedFix:"Add the required action with provenance from the original requirement and connect it according to the requirement contract before allowing termination."});
  }
  // Conservative extra-step detection: only executable business nodes are considered.
  // Structural nodes (trigger/condition/approval/join/end) are never called redundant here.
  const reqActions=(contract.requiredActions||[]).map(x=>String(x));
  const verb=(x:string)=>(x.toLowerCase().match(/\b(create|assign|notify|email|message|alert|schedule|classify|escalate|route|send|check|verify|validate|update|save|store|call|request|obtain|extract|match|process|record|open|close|archive|log|publish|sync|upload|download|transform|convert|calculate|compute|fetch|get|read|write|generate)\b/)||[])[1]||"";
  const extraKinds=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay"]);
  for(const n of nodes.filter(n=>extraKinds.has(n.type)&&String((n.config||{}).Inferred||"").toLowerCase()!=="true")){const nv=verb(nodeText(n));if(!nv)continue;const grounded=reqActions.some(a=>{const av=verb(a);if(av&&av!==nv)return false;const aw=tokens(a).filter(t=>t!==av),nw=tokens(nodeText(n)).filter(t=>t!==nv);if(!aw.length)return av===nv;const overlap=aw.filter(t=>nw.includes(t)).length;return overlap/Math.max(1,aw.length)>=0.6;});if(!grounded)findings.push({id:`extra-step-${n.id}`,severity:"error",title:`Extra/Unrequested Step: ${n.name}`,category:"Requirement Semantics",reason:`This business step cannot be grounded in an action requested by the original requirement.`,affected:[n.id],suggestedFix:"Remove it only if semantic review confirms it is not required; otherwise rewrite the node so its required purpose is explicit."});}
  const hasPath=(from:string,to:string)=>{const seen=new Set<string>();const q=[from];while(q.length){const id=q.shift()!;if(id===to&&id!==from)return true;if(seen.has(id))continue;seen.add(id);for(const e of outgoing.get(id)||[])q.push(e.target);}return false;};
  const executable=new Set<SharedNodeType>(["action","api","webhook","database","notification","delay","approval","condition","end"]);
  for(let ci=0;ci<contract.mustFollow.length;ci++){const c=contract.mustFollow[ci];const before=findNode(nodes,c.before,executable),after=findNode(nodes,c.after,executable);if(!before||!after||before.id===after.id)continue;if(!hasPath(before.id,after.id)){const reversed=hasPath(after.id,before.id);findings.push({id:`dependency-${ci}-${before.id}-${after.id}`,severity:"error",title:"Requirement Dependency/Order Violated",category:"Requirement Semantics",reason:reversed?`The graph executes '${after.name}' before '${before.name}', but the requirement states the opposite dependency/order.`:`The required step '${after.name}' is not downstream of '${before.name}'.`,affected:[before.id,after.id],suggestedFix:`Ensure ${before.name} occurs before ${after.name} on the same required path.`});}}
  for(let bi=0;bi<contract.branches.length;bi++){const b=contract.branches[bi];let anchor:SharedNode|undefined;if(["APPROVED","REJECTED","TIMEOUT"].includes(b.branch)){const aps=nodes.filter(n=>n.type==="approval");anchor=aps.length===1?aps[0]:findNode(nodes,b.anchor,new Set<SharedNodeType>(["approval"]));}else{anchor=findNode(nodes,b.anchor,new Set<SharedNodeType>(["condition"]));if(!anchor){const cs=nodes.filter(n=>n.type==="condition");if(cs.length===1)anchor=cs[0];}}if(!anchor)continue;const start=(outgoing.get(anchor.id)||[]).find(e=>String(e.branch||"DEFAULT").toUpperCase()===b.branch)?.target;if(!start){findings.push({id:`branch-missing-${bi}-${anchor.id}-${b.branch}`,severity:"error",title:`Missing Required ${b.branch} Branch`,category:"Requirement Semantics",reason:`The original requirement explicitly defines a ${b.branch} outcome for '${anchor.name}', but the graph has no such branch.`,affected:[anchor.id],suggestedFix:`Add the ${b.branch} branch grounded in the stated requirement.`});continue;}const branchReachable=(target:string)=>start===target||hasPath(start,target);let prev:string|undefined;for(let ai=0;ai<b.actions.length;ai++){const action=findNode(nodes,b.actions[ai],executable);if(!action)continue;if(!branchReachable(action.id))findings.push({id:`branch-position-${bi}-${ai}-${action.id}`,severity:"error",title:"Required Action Is On Wrong Branch",category:"Requirement Semantics",reason:`'${action.name}' exists, but it is not reachable from ${anchor.name} / ${b.branch} as required.`,affected:[anchor.id,action.id],suggestedFix:`Place ${action.name} on the ${b.branch} path from ${anchor.name}.`});if(prev&&!hasPath(prev,action.id))findings.push({id:`branch-order-${bi}-${ai}-${action.id}`,severity:"error",title:"Branch Action Order Violated",category:"Requirement Semantics",reason:`The ${b.branch} branch must execute the stated actions in order; '${action.name}' is not downstream of the previous required action.`,affected:[prev,action.id],suggestedFix:"Restore the original branch action sequence."});prev=action.id;}}
  const explicitLoopIntent=/\b(repeat|repeating|retry|again|keep checking|keep repeating|continue until|until|while|loop)\b/i.test(prompt);
  const cyclic=cycleComponents(nodes,edges);for(let idx=0;idx<cyclic.length;idx++){const comp=cyclic[idx],set=new Set(comp),exits=edges.filter(e=>set.has(e.source)&&!set.has(e.target)),decisions=nodes.filter(n=>set.has(n.id)&&n.type==="condition"),controlled=exits.some(e=>decisions.some(n=>n.id===e.source));if(!explicitLoopIntent)findings.push({id:`cycle-${idx+1}`,severity:"error",title:"Unexpected Cycle Detected",category:"Graph Integrity",reason:`Cycle ${comp.join(" → ")} exists even though the original requirement does not request repetition.`,affected:comp,suggestedFix:"Remove the accidental back-edge and restore the requested acyclic action order."});else if(!exits.length)findings.push({id:`cycle-${idx+1}`,severity:"error",title:"Infinite Loop Detected",category:"Graph Integrity",reason:`Cycle ${comp.join(" → ")} has no edge leaving the cycle.`,affected:comp,suggestedFix:"Add a condition-controlled exit path from the loop."});else if(!controlled){const crossesJoin=nodes.some(n=>set.has(n.id)&&n.type==="join");findings.push({id:`cycle-${idx+1}`,severity:crossesJoin?"error":"warning",title:crossesJoin?"Uncontrolled Loop Crosses Join":"Potentially Unbounded Loop",category:"Graph Integrity",reason:crossesJoin?`Cycle ${comp.join(" → ")} crosses a Join but has no deterministic condition-controlled exit. Join state must not be reused across uncontrolled iterations.`:`Cycle ${comp.join(" → ")} has an exit, but the exit is not clearly controlled by a condition inside the loop.`,affected:comp,suggestedFix:"Connect an explicit condition outcome to the loop exit."});}}
  return [...new Map(findings.map(f=>[f.id,f])).values()];
}


export function evaluateTargetedRepairInvariant(
  prompt:string,
  beforeNodes:SharedNode[], beforeEdges:SharedEdge[],
  afterNodes:SharedNode[], afterEdges:SharedEdge[],
  targetIssueIds:string[]
){
  const target=new Set(targetIssueIds);
  const before=new Set(evaluateSharedStructuralRules(prompt,beforeNodes,beforeEdges).filter(f=>f.severity==="error").map(f=>f.id));
  const after=new Set(evaluateSharedStructuralRules(prompt,afterNodes,afterEdges).filter(f=>f.severity==="error").map(f=>f.id));
  const remaining=[...target].filter(id=>after.has(id));
  const introduced=[...after].filter(id=>!before.has(id));
  return {success:target.size>0&&remaining.length===0&&introduced.length===0,remaining,introduced};
}

export function sharedProblems(prompt:string,nodes:SharedNode[],edges:SharedEdge[]):string[]{return evaluateSharedStructuralRules(prompt,nodes,edges).map(f=>`${f.title}: ${f.reason} Suggested: ${f.suggestedFix}`);}
