import { createFileRoute } from "@tanstack/react-router";
import { Braces, Copy, Download, Globe2, Plug, Webhook } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { PageIntro } from "@/components/common/PageIntro";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export const Route = createFileRoute("/integrations")({ component: IntegrationsPage });
const cards=[{title:'Webhook',desc:'Trigger this workflow from any external application.',icon:Webhook,code:'POST /api/workflows/wf-purchase/trigger'},{title:'REST API',desc:'Start runs and retrieve execution state programmatically.',icon:Globe2,code:'POST /v1/executions { workflowId: "wf-purchase" }'},{title:'JavaScript SDK',desc:'Embed workflow triggers inside a web application.',icon:Braces,code:'flowforge.run("wf-purchase", payload)'},{title:'Export JSON',desc:'Move the portable workflow IR into another environment.',icon:Download,code:'purchase-approval.workflow.json'}];
function IntegrationsPage(){return <AppShell><PageIntro eyebrow="Deploy & Connect" title="Use the workflow in any project." description="The verified workflow is portable. Connect through webhooks, REST, an SDK or export the intermediate representation."/><div className="grid gap-4 md:grid-cols-2">{cards.map(({title,desc,icon:Icon,code})=><div key={title} className="rounded-2xl border bg-card/70 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4"/></span><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{desc}</p><div className="mt-4 flex items-center gap-2 rounded-xl border bg-background/50 p-3 font-mono text-[11px] text-primary"><code className="min-w-0 flex-1 truncate">{code}</code><Button variant="ghost" size="icon" onClick={()=>{navigator.clipboard?.writeText(code);toast.success('Copied')}}><Copy className="h-3.5 w-3.5"/></Button></div></div>)}</div><div className="mt-6 rounded-2xl border bg-card/60 p-5"><div className="flex items-center gap-2 text-sm font-semibold"><Plug className="h-4 w-4 text-ai"/> Integration targets</div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{['Website','Mobile App','Backend','CRM / ERP','Custom App'].map(x=><div key={x} className="rounded-xl border bg-surface/50 p-4 text-center text-xs font-medium">{x}</div>)}</div></div></AppShell>}
