import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Download, ExternalLink, FileUp, Play, Trash2, Workflow } from "lucide-react";
import { useRef, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { PageIntro } from "@/components/common/PageIntro";
import { Button } from "@/components/ui/button";
import { flowActions } from "@/lib/workflow-store";
import { deleteSavedWorkflow, downloadWorkflowFile, importWorkflowFileText, listSavedWorkflows } from "@/lib/workflow-library";
export const Route=createFileRoute('/library')({component:LibraryPage});
function LibraryPage(){
  const navigate=useNavigate();const inputRef=useRef<HTMLInputElement>(null);const [rev,setRev]=useState(0);const [error,setError]=useState<string|null>(null);
  const workflows=listSavedWorkflows();void rev;
  const open=(id:string,to:"/studio"|"/executions"="/studio")=>{if(flowActions.loadSavedWorkflow(id))navigate({to});};
  const importFile=async(file?:File)=>{if(!file)return;try{const w=importWorkflowFileText(await file.text());setError(null);setRev(x=>x+1);open(w.id);}catch(e){setError(e instanceof Error?e.message:String(e));}};
  return <AppShell><PageIntro eyebrow="Certified Workflow Library" title="Only execution-proven workflows are saved." description="A workflow appears here only after structural verification, semantic verification, and every mandatory execution scenario passes. Exported .flowforge.json files contain the prompt, graph, configuration, tests, and certification evidence." actions={<><input ref={inputRef} type="file" accept=".json,.flowforge.json,application/json" className="hidden" onChange={e=>importFile(e.target.files?.[0])}/><Button variant="outline" onClick={()=>inputRef.current?.click()}><FileUp className="h-4 w-4"/> Import workflow</Button></>}/>{error&&<div className="mb-4 rounded-xl border border-danger/30 bg-danger/5 p-3 text-xs text-danger">{error}</div>}{!workflows.length?<div className="rounded-2xl border bg-card/60 p-10 text-center"><Workflow className="mx-auto h-8 w-8 text-muted-foreground"/><div className="mt-3 text-sm font-semibold">No certified workflows yet</div><div className="mt-1 text-xs text-muted-foreground">Verify a workflow, run the full certification suite, and it will be saved automatically only if every required scenario passes.</div></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{workflows.map(w=><div key={w.id} className="rounded-2xl border bg-card/70 p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-success/10 text-success"><Workflow className="h-4 w-4"/></span><span className="rounded-full border border-success/30 bg-success/5 px-2 py-1 text-[9px] font-bold text-success">CERTIFIED</span></div><h2 className="mt-4 text-lg font-semibold">{w.name}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-muted-foreground">{w.sourcePrompt}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-surface-2 p-2"><b className="text-sm">{w.nodes.length}</b><div className="text-[9px] text-muted-foreground">Nodes</div></div><div className="rounded-lg bg-surface-2 p-2"><b className="text-sm">{w.certificationResults.length}</b><div className="text-[9px] text-muted-foreground">Tests passed</div></div><div className="rounded-lg bg-surface-2 p-2"><b className="text-sm">{w.verification.score}</b><div className="text-[9px] text-muted-foreground">Verify score</div></div></div><div className="mt-4 flex gap-2"><Button size="sm" className="flex-1" onClick={()=>open(w.id)}><ExternalLink className="h-3.5 w-3.5"/> Open</Button><Button size="sm" variant="outline" onClick={()=>open(w.id,"/executions")} title="Open execution tests"><Play className="h-3.5 w-3.5"/></Button><Button size="sm" variant="outline" onClick={()=>downloadWorkflowFile(w)} title="Download portable workflow"><Download className="h-3.5 w-3.5"/></Button><Button size="sm" variant="outline" onClick={()=>{deleteSavedWorkflow(w.id);setRev(x=>x+1)}} title="Delete saved copy"><Trash2 className="h-3.5 w-3.5"/></Button></div></div>)}</div>}</AppShell>
}
