import { createFileRoute } from "@tanstack/react-router";
import { Bell, Bot, Database, KeyRound, Save } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { PageIntro } from "@/components/common/PageIntro";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
export const Route=createFileRoute('/settings')({component:SettingsPage});
function SettingsPage(){const groups=[{icon:Bot,title:'AI Compiler',desc:'Model and compiler behavior'},{icon:KeyRound,title:'Secrets & API Keys',desc:'External connector credentials'},{icon:Database,title:'Persistence',desc:'Workflow and execution storage'},{icon:Bell,title:'Notifications',desc:'Execution and verification alerts'}]; return <AppShell><PageIntro eyebrow="Configuration" title="Project settings" description="Frontend placeholders for the services that will be connected in the backend phase."/><div className="grid gap-4 lg:grid-cols-2">{groups.map(({icon:Icon,title,desc},i)=><div key={title} className="rounded-2xl border bg-card/70 p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4"/></span><div><h2 className="text-sm font-semibold">{title}</h2><p className="text-[11px] text-muted-foreground">{desc}</p></div></div><div className="mt-5 space-y-4">{i===0&&<><div><Label>Compiler provider</Label><Input className="mt-1.5 bg-surface/50" value="NVIDIA NIM / LM Studio (server-configured)" readOnly/></div><div className="flex items-center justify-between"><Label>Strict schema validation</Label><Switch defaultChecked/></div></>}{i===1&&<><div><Label>API key</Label><Input className="mt-1.5 bg-surface/50" placeholder="Connect in backend phase" type="password"/></div><div className="flex items-center justify-between"><Label>Encrypt secrets at rest</Label><Switch defaultChecked/></div></>}{i===2&&<><div><Label>Database</Label><Input className="mt-1.5 bg-surface/50" value="Firebase / Firestore (planned)" readOnly/></div><div className="flex items-center justify-between"><Label>Store execution history</Label><Switch defaultChecked/></div></>}{i===3&&<><div className="flex items-center justify-between"><Label>Verification failures</Label><Switch defaultChecked/></div><div className="flex items-center justify-between"><Label>Execution failures</Label><Switch defaultChecked/></div></>}</div></div>)}</div><div className="mt-5 flex justify-end"><Button onClick={()=>toast.success('Settings saved')}><Save className="h-4 w-4"/> Save Settings</Button></div></AppShell>}
