import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Bot, CheckCircle2, GitCompareArrows, Loader2, RefreshCcw, ShieldCheck, Sparkles, XCircle } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { PageIntro } from "@/components/common/PageIntro";
import { Button } from "@/components/ui/button";
import { WorkflowCanvas } from "@/components/workflow/WorkflowCanvas";
import { flowActions, useFlowState } from "@/lib/workflow-store";

export const Route=createFileRoute("/verification")({component:VerificationPage});
function statusText(status:string){if(status==="VERIFIED")return "Verified";if(status==="NEEDS USER INPUT")return "Needs user input";if(status==="RUNNING")return "Analyzing";if(status==="ISSUES FOUND")return "Needs regeneration";return "Not verified";}

function VerificationPage(){
  const s=useFlowState();const unresolved=s.issues.filter(i=>i.severity!=="pass"&&!i.resolved);const proposal=s.semanticProposal;const busy=s.verifying||s.semanticReviewRunning;const needsInput=proposal?.findings.some(f=>f.requiresUserInput)||proposal?.correctedWorkflow.ambiguities.some(a=>a.requiresUserInput);
  return <AppShell>
    <PageIntro eyebrow="Verification Engine" title="Judge the whole workflow. Regenerate when wrong." description="FlowForge audits the complete graph against the original requirement. If the workflow is wrong, the old graph is never patched: the model regenerates one complete replacement and deterministic validation decides whether it can replace the old graph." actions={<>
      <Button variant="outline" onClick={()=>flowActions.verify()} disabled={busy||!s.nodes.length}><RefreshCcw className="h-4 w-4"/> Static Scan</Button>
      <Button onClick={()=>flowActions.verifyAndReview()} disabled={busy||!s.nodes.length||!s.prompt.trim()} className="bg-primary text-primary-foreground">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{s.verifying?"Structural scan…":s.semanticReviewRunning?"Model judging…":"Verify + Regenerate if Wrong"}</Button>
    </>}/>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-4"><div className="h-[570px] overflow-hidden rounded-2xl border bg-card/45"><WorkflowCanvas interactive={false} focusNodeId={unresolved[0]?.affected[0]}/></div><div className="rounded-2xl border bg-card/60 p-4"><div className="flex items-start gap-3"><Bot className="mt-0.5 h-4 w-4 text-ai"/><div><div className="text-xs font-semibold">Original requirement — business source of truth</div><div className="mt-1 text-[11px] leading-5 text-muted-foreground">{s.prompt||"Compile a workflow first."}</div></div></div></div></div>
      <div className="space-y-4">
        <div className="rounded-2xl border bg-card/70 p-5"><div className="flex items-center justify-between"><div><div className="text-[11px] font-bold tracking-widest text-muted-foreground uppercase">Verification State</div><div className="mt-1 text-2xl font-bold">{statusText(s.status)}</div><div className="mt-1 text-xs text-muted-foreground">Deterministic score: {s.score||"—"} / 100</div></div><div className={`grid h-14 w-14 place-items-center rounded-full ${s.status==='VERIFIED'?'bg-success/15 text-success':s.status==='NEEDS USER INPUT'?'bg-warning/15 text-warning':'bg-primary/10 text-primary'}`}>{s.status==='VERIFIED'?<CheckCircle2/>:<ShieldCheck/>}</div></div><div className="mt-4 grid grid-cols-2 gap-2 text-[11px]"><div className="rounded-xl border bg-background/40 p-3"><div className="font-semibold">Current static issues</div><div className="mt-1 text-lg font-bold">{unresolved.length}</div></div><div className="rounded-xl border bg-background/40 p-3"><div className="font-semibold">Replacement differences</div><div className="mt-1 text-lg font-bold">{proposal?.diff.length??"—"}</div></div></div></div>
        {s.verifyLog.length>0&&<div className="max-h-44 overflow-auto rounded-2xl border bg-background/55 p-4 font-mono text-[11px] leading-6 text-muted-foreground">{s.verifyLog.map((x,i)=><div key={`${x}-${i}`}>› {x}</div>)}</div>}
        {s.semanticReviewError&&<div className="rounded-2xl border border-danger/35 bg-danger/5 p-4"><div className="flex gap-3"><XCircle className="mt-0.5 h-4 w-4 shrink-0 text-danger"/><div><div className="text-sm font-semibold">Verification model failed</div><div className="mt-1 text-[11px] leading-5 text-muted-foreground">{s.semanticReviewError}</div><Button size="sm" variant="outline" className="mt-3" onClick={()=>flowActions.semanticReview()}><Bot className="h-3.5 w-3.5"/> Retry whole-workflow verdict</Button></div></div></div>}
        {proposal&&<div className={`rounded-2xl border p-4 ${needsInput?'border-warning/35 bg-warning/5':s.status==='VERIFIED'?'border-success/30 bg-success/5':'border-ai/30 bg-ai/5'}`}><div className="flex items-start gap-3"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-ai"/><div className="min-w-0 flex-1"><div className="text-sm font-semibold">Whole-workflow verdict</div><div className="mt-1 text-[11px] leading-5 text-muted-foreground">{proposal.reviewSummary}</div><div className="mt-2 text-[10px] text-muted-foreground">{proposal.model} · {(proposal.durationMs/1000).toFixed(1)}s</div></div></div>{proposal.findings.length>0&&<div className="mt-4 space-y-2">{proposal.findings.map(f=><div key={f.id} className="rounded-xl border bg-background/45 p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${f.requiresUserInput?'bg-warning':f.severity==='error'?'bg-danger':'bg-success'}`}/><div className="text-xs font-semibold">{f.title}</div>{f.requiresUserInput&&<span className="ml-auto rounded-full bg-warning/10 px-2 py-0.5 text-[9px] font-bold text-warning">NEEDS INPUT</span>}</div><div className="mt-1 text-[10px] leading-5 text-muted-foreground">{f.reason}</div></div>)}</div>}</div>}
        {proposal&&proposal.diff.length>0&&<div className="rounded-2xl border bg-card/70 p-4"><div className="flex items-center gap-2"><GitCompareArrows className="h-4 w-4 text-primary"/><div className="text-sm font-semibold">Atomic replacement audit</div><span className="ml-auto rounded-full border px-2 py-0.5 text-[10px]">{proposal.diff.length}</span></div><div className="mt-2 text-[10px] leading-5 text-muted-foreground">These are differences between the previous graph and the complete regenerated candidate. They are not patch operations. When the candidate passes deterministic validation, the complete graph is replaced automatically.</div><div className="mt-3 max-h-56 space-y-2 overflow-auto">{proposal.diff.map((d,i)=><div key={`${d.id}-${i}`} className="rounded-xl border bg-background/40 p-3"><div className="text-[11px] font-semibold">{d.change.toUpperCase()} · {d.label}</div><div className="mt-0.5 text-[10px] leading-4 text-muted-foreground">{d.detail}</div></div>)}</div></div>}
        {s.status==='ISSUES FOUND'&&<div className="rounded-2xl border border-danger/30 bg-danger/5 p-4"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 text-danger"/><div><div className="text-sm font-semibold">No replacement was accepted</div><div className="mt-1 text-[11px] text-muted-foreground">The current graph remains unchanged. FlowForge will not apply partial repairs or certify an invalid regenerated candidate.</div></div></div></div>}
        <div className="space-y-3">{s.issues.filter(i=>i.severity!=="pass").map(issue=><div key={issue.id} className={`rounded-2xl border p-4 ${issue.severity==='error'?'border-danger/35 bg-danger/5':'border-warning/35 bg-warning/5'}`}><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><div><div className="text-sm font-semibold">{issue.title}</div><div className="mt-1 text-[11px] leading-5 text-muted-foreground">{issue.reason}</div></div></div></div>)}</div>
        {s.status==='VERIFIED'&&<Button asChild className="w-full bg-success text-background hover:bg-success/90"><Link to="/executions">Run Verified Workflow <ArrowRight className="h-4 w-4"/></Link></Button>}
      </div>
    </div>
  </AppShell>;
}
