import { useEffect, useState } from "react";
import { Copy, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { NODE_META } from "./nodeMeta";
import { flowActions, useFlowState } from "@/lib/workflow-store";
import type { NodeKind } from "@/lib/types";
import { completeNodeConfig } from "@/lib/node-contracts";
import { toast } from "sonner";

const kinds:NodeKind[]=["trigger","action","condition","approval","api","webhook","database","notification","delay","join","end"];
export function NodeConfiguration(){
  const s=useFlowState(); const node=s.nodes.find(n=>n.id===s.selectedNodeId); const [name,setName]=useState(""); const [kind,setKind]=useState<NodeKind>("action"); const [subtitle,setSubtitle]=useState(""); const [config,setConfig]=useState<Record<string,string>>({}); const [newKey,setNewKey]=useState("");
  useEffect(()=>{if(node){setName(node.data.name);setKind(node.data.kind);setSubtitle(node.data.subtitle||"");setConfig({...node.data.config});}},[node?.id,node?.data.name,node?.data.kind,node?.data.subtitle,node?.data.config]);
  if(!node)return null; const meta=NODE_META[node.data.kind];
  const addField=()=>{const k=newKey.trim();if(!k||k in config)return;setConfig(c=>({...c,[k]:""}));setNewKey("");};
  return <div className="glass flex h-full w-[360px] shrink-0 flex-col border-l"><div className="flex items-center justify-between border-b px-5 py-4"><div><div className="text-[10px] font-semibold tracking-widest text-muted-foreground uppercase">{meta.label} configuration</div><h3 className="text-[15px] font-semibold">{node.data.name}</h3></div><Button variant="ghost" size="icon" onClick={()=>flowActions.setSelected(null)}><X className="h-4 w-4"/></Button></div>
  <div className="flex-1 space-y-4 overflow-y-auto px-5 py-4"><div className="space-y-1.5"><Label className="text-[11px] text-muted-foreground">Node type</Label><select value={kind} onChange={e=>{const next=e.target.value as NodeKind;setKind(next);setConfig(c=>completeNodeConfig(next,name,subtitle,c));}} className="h-10 w-full rounded-md border border-input bg-surface-2/60 px-3 text-sm">{kinds.map(k=><option key={k} value={k}>{k}</option>)}</select></div><div className="space-y-1.5"><Label className="text-[11px] text-muted-foreground">Node name</Label><Input value={name} onChange={e=>setName(e.target.value)} className="bg-surface-2/60"/></div><div className="space-y-1.5"><Label className="text-[11px] text-muted-foreground">Description / purpose</Label><Textarea value={subtitle} onChange={e=>setSubtitle(e.target.value)} className="min-h-20 bg-surface-2/60"/></div>
  <div className="border-t pt-4"><div className="mb-3 flex items-center justify-between"><div className="text-[10px] font-bold tracking-widest text-muted-foreground uppercase">Behavior & parameters</div><button onClick={()=>setConfig(c=>completeNodeConfig(kind,name,subtitle,c))} className="text-[10px] font-semibold text-primary hover:underline">Fill safe defaults</button></div>{Object.entries(config).map(([k,v])=><div key={k} className="mb-3 rounded-xl border bg-background/30 p-2.5"><div className="mb-1.5 flex items-center justify-between"><Label className="text-[11px] text-muted-foreground">{k}</Label><button onClick={()=>setConfig(c=>Object.fromEntries(Object.entries(c).filter(([key])=>key!==k)))} className="text-muted-foreground hover:text-danger"><X className="h-3 w-3"/></button></div><Input value={v} onChange={e=>setConfig(c=>({...c,[k]:e.target.value}))} className="bg-surface-2/60 font-mono text-[12px]"/></div>)}<div className="flex gap-2"><Input value={newKey} onChange={e=>setNewKey(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addField()} placeholder="Add parameter e.g. URL, Role, Expression" className="bg-surface-2/60 text-xs"/><Button size="icon" variant="outline" onClick={addField}><Plus className="h-4 w-4"/></Button></div></div>
  {(["api","database","webhook","notification"].includes(kind))&&<div className="rounded-xl border bg-primary/5 p-3 text-[10px] leading-5 text-muted-foreground">{kind==="api"?"TEST mode uses MockStatus/MockResponse. When an I/O node branches, TRUE means success and FALSE means failure.":kind==="notification"?"RecipientRole + Message are enough for semantic/test execution. TRUE means delivered/success and FALSE means failure when branches are present.":"I/O outcome contract: TRUE = success, FALSE = failure. Concrete deployment connection details may be supplied later."}</div>}
  {node.data.issue&&<div className="rounded-xl border border-danger/40 bg-danger/10 p-3 text-[12px] text-danger">{node.data.issue}</div>}</div>
  <div className="grid grid-cols-[1fr_auto_auto] gap-2 border-t px-5 py-4"><Button className="bg-primary text-primary-foreground" onClick={()=>{flowActions.updateNode(node.id,kind,name,subtitle,config);toast.success("Node behavior updated");}}>Save</Button><Button variant="outline" size="icon" onClick={()=>flowActions.duplicateNode(node.id)}><Copy className="h-4 w-4"/></Button><Button variant="outline" size="icon" className="border-danger/40 text-danger" onClick={()=>{flowActions.deleteNode(node.id);toast("Node deleted");}}><Trash2 className="h-4 w-4"/></Button></div></div>;
}
